[package]
name = "graphql_client_cli"
description = "The CLI for graphql-client"
version = "0.7.1"
authors = ["Tom Houlé <tom@tomhoule.com>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/graphql-rust/graphql-client"
edition = "2018"

[[bin]]
name = "graphql-client"
path = "src/main.rs"

[dependencies]
failure = "0.1"
reqwest = "^0.9.0"
graphql_client = { version = "0.7.1", path = "../graphql_client" }
graphql_client_codegen = { path = "../graphql_client_codegen/", version = "0.7.1" }
structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = "0.15"
log = "0.4.0"
env_logger = "0.6.0"

rustfmt-nightly = { version = "0.99" , optional = true }

[features]
default = []
rustfmt = ["rustfmt-nightly"]
